version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the root folder that contains .git
      - ..:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    user: node

  db:
    image: postgres:16.2-bullseye
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Asd123
      POSTGRES_DB: bioledger

volumes:
  db:
    driver: local
